wandb_name: ali_cfm
wandb_mode: online
saved_run_dir: none
seed_list: [42]

dim: 2
net_hidden: 256
n_data_dims: ${dim}
whiten: false
dataset: cell_tracking
normalize_dataset: False
device: cuda:0
batch_size: 128

interpolant_ot: border
cfm_ot: border

n_ot_cfm_epochs: 50_001
num_int_steps_per_timestep: 500

train_cfm: True

hydra:
  run:
    dir: .