wandb_name: cfm
wandb_mode: offline

seed_list: [42, 43, 44, 45, 46]

dataset: cite
dim: 5
n_data_dims: ${dim}
whiten: true
normalize_dataset: false

net_hidden: 64
time_varying: true
device: 'mps'
batch_size: 128
lr: 1e-3
weight_decay: 1e-5

interpolant: linear-ot

n_iter: 1_001
num_int_steps_per_timestep: 100

hydra:
  run:
    dir: .