wandb_name: debug
wandb_mode: disabled
saved_run_dir: none
seed_list: [42, 43, 44, 45, 46]
device: mps

# dataset params
dataset: multi
dim: 50
whiten: false
normalise: true

# networks' params
t_smooth: 0.01
cfm_dim: 1024
interpolant_dim: 1024
disc_dim: 1024

# ot params
pretain_ot: full
interpolant_ot: mmot
cfm_ot: mmot

# training params
batch_size: 128
correct_coeff: 0.0001

num_ali_pretrain_steps: 10
pretrain_lr: 1e-3

reg_metric: 'l2'
land_gamma: 0.2
land_t_gamma: 0.2

reg_term_type: 'linear'
num_t_steps: 10
gan_loss: RpGAN
interpolant_gen_lr: 5e-5
interpolant_disc_lr: 5e-5
num_ali_train_steps: 10

cfm_lr: 1e-3
num_cfm_train_steps: 10

use_pca: false
train_cfm: true
train_interpolants: true
num_int_steps_per_timestep: 100
trajectory_simulation_batch_size: 2048

# hudra params
hydra:
  run:
    dir: .